package com.zekiyetekin.onlineBlogging.enumuration;

public enum ResponseMessageEnum {

    LISTING_SUCCESSFULLY_DONE,
    BAD_REQUEST,
    SUCCESSFULLY_DONE,
    USERS_NOT_FOUND,
    DATA_NOT_FOUND,
    NOT_ACCEPTABLE,
    CREATED_SUCCESSFULLY,
    SEARCHED_SUCCESSFULLY,
    SEARCHED_ERROR,
    CREATED_ERROR,
    UPDATED_SUCCESSFULLY_DONE,
    UPDATED_ERROR,
    DELETED_SUCCESSFULLY_DONE,
    DELETED_ERROR,
}
